services:
    postgres:
        image: postgres:16
        container_name: pg_test
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ${PGDATABASE}
            TZ: UTC
        command: ["postgres", "-c", "timezone=UTC"]
        volumes:
            - pgdata:/var/lib/postgresql/data

    node-app:
        build: .
        container_name: test_runner
        depends_on:
            - postgres
        env_file:
            - .env.test
        environment:
            NODE_ENV: test
            DOCKER: true
            TZ: UTC
        command: >
            bash -c "./scripts/wait-for-it.sh postgres:5432 --timeout=30 --strict -- node scripts/reset-test-db.js && npm test"

volumes:
    pgdata:
