name: PR Deploy & Test (Staging)
run-name: ${{ github.actor }} is deploying to Staging 🚀

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    test:
        name: Test Execution
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Set up PostgreSQL
              uses: harmon758/postgresql-action@v1
              with:
                  postgresql db: "nc_news_test"
                  postgresql user: "test_user"
                  postgresql password: "password"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: PGDATABASE=nc_news_test PGUSER=test_user PGPASSWORD=password npm t

    deploy:
        name: Deploy PR to Staging
        runs-on: ubuntu-latest
        needs: test
        permissions:
            deployments: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set branch variable
              run: echo "PR_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

            - name: Update Render staging service to PR branch
              run: |
                  echo "Updating Render service to branch: $PR_BRANCH"
                  curl -X PATCH \
                    -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
                    -H "Content-Type: application/json" \
                    -d "{\"branch\": \"${PR_BRANCH}\"}" \
                    https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_STAGING }}

            - name: Deploy to Render staging
              uses: JorgeLNJunior/render-deploy@v1.4.5
              with:
                  service_id: ${{ secrets.RENDER_SERVICE_ID_STAGING }}
                  api_key: ${{ secrets.RENDER_API_KEY }}
                  clear_cache: false
                  wait_deploy: true
                  github_deployment: true
                  deployment_environment: "staging"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
